### ISSUE TITLE
can i use this lib in react or vue?

### ISSUE THREAD

**Issue by ericzhao1979** [dmotz/oriDomi#52]
React and vue using MVVM to render dom,
If i use this lib, maybe i have to use modifyContent frequently?
Is there a demo about this?

**Comment by dmotz** [comment]
Yes, since behind the scenes OriDomi is creating numerous DOM element clones, you'll have to make updates via `modifyContent` in your `componentDidUpdate`. You should also avoid letting React or Vue remove the initial element you give to the OriDomi instance, similar to how you might use a canvas element in these frameworks.

**Comment by ericzhao1979** [comment]
thanks for your reply.
